[package]
org = "luis_p_shinyala"
name = "Client"
version = "0.1.0"
distribution = "2201.10.1"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
path= # add the path to your database connector and add an extra \ to the \
