services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306

  Central-Logistics-Service:
    build:
      context: services/logistics
      dockerfile: Dockerfile
    platform: linux/arm64/v8
    depends_on:
      - kafka
    environment:
      - KAFKA_URL=kafka:29092

  Standard-Delivery-Service:
    build:
      context: services/standard
      dockerfile: Dockerfile
    platform: linux/arm64/v8
    depends_on:
      - kafka
    environment:
      - KAFKA_URL=kafka:29092

  Express-Delivery-service:
    build:
      context: services/express
      dockerfile: Dockerfile
    platform: linux/arm64/v8
    depends_on:
      - kafka
    environment:
      - KAFKA_URL=kafka:29092

  International-Delivery-service:
    build:
      context: services/international
      dockerfile: Dockerfile
    platform: linux/arm64/v8
    depends_on:
      - kafka
    environment:
      - KAFKA_URL=kafka:29092

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    platform: linux/arm64/v8
    depends_on:
      - kafka
      - mysql
    environment:
      - KAFKA_URL=kafka:29092
      - MYSQL_URL=mysql:3306
