version: '3.7'

services:
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "logistics_db"
  central-logistics-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - kafka
      - mysql
  standard-delivery-service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - mysql
  express-delivery-service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - mysql
  international-delivery-service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - mysql
